version: '3.8'

services:
  app:
    build:
      context: . 
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT:-3000}:${APP_PORT:-3000}" 
    volumes:
      - .:/usr/src/app 
      - /usr/src/app/node_modules 
    depends_on:
      - db
    environment:
      - NODE_ENV=development
      - APP_PORT=${APP_PORT:-3000}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db 
      - DB_PORT=${DB_PORT:-5432}
      - DB_NAME=${DB_NAME}
    networks:
      - chocolatenet

  db:
    image: postgres:15-alpine
    ports:
      - "${DB_PORT:-5432}:5432" 
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql 
      - postgres_data:/var/lib/postgresql/data 
    networks:
      - chocolatenet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  

volumes:
  postgres_data:

networks:
  chocolatenet:
    driver: bridge